name: CI/CD for MCP Server

on: 
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build-and-test:
    name: Build, Test, and AI Scan
    runs-on: ubuntu-latest

    # set the working dir for all steps in this job
    defaults:
      run:
        working-directory: ./app/mcp-server   # can be modified ...

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
      
    - name: Install dependency
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run Unit Tests
      run: |
        if [ -d tests ]; then
          python -m unittest discover -s tests
        else
          echo "No tests directory found, skipping tests."
        fi

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3


  # this runs on every pull request to validate the deployment process
  deploy-to-staging:
    name: Deploy to Staging
    needs: build-and-test
    runs-on: self-hosted
    # "if" condition so this job runs only on pull req 
    if: github.event_name == 'pull_request'
    
    defaults:
      run:
        working-directory: ./app/mcp-server
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest

    - name: Build Docker Image in Minikube
      run: |
        eval $(minikube docker-env)
        # Build the final image with the ':latest' tag
        docker build -t mcp-server:latest .

    - name: Deploy Unique Staging Resources
      run: |
        # Apply the original, unmodified Kubernetes manifest
        kubectl apply -f k8s/deployment.yaml

        # Check the rollout status of the static deployment
        kubectl rollout status deployment/mcp-server



  deploy-to-production:
    name: Deploy to Minikube
    needs: build-and-test
    runs-on: self-hosted

    # set the working dir for all steps in this job
    defaults:
      run:
        working-directory: ./app/mcp-server   # can be modified 

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Start Minikube
      uses: medyagh/setup-minikube@latest

    - name: Build Production Docker Image
      run: |
        eval $(minikube docker-env)
        # Build the final image with the ':latest' tag
        docker build -t mcp-server:latest .

    - name: Deploy to Production
      run: |
        # Apply the original, unmodified Kubernetes manifest
        kubectl apply -f k8s/deployment.yaml

        # Check the rollout status of the static deployment
        kubectl rollout status deployment/mcp-server

    - name: Test Production Service URL
      run: |
        echo "Displaying all services and their ports in the cluster:"
        minikube service list